name: 'Electronegativity'

on:
  pull_request:
    branches: [main]

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version-file: .nvmrc

      - uses: doyensec/electronegativity-action@a8facd6408075fc604fa8850d508319526ae7cd1 # v1.1

      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@8a470fddafa5cbb6266ee11b37ef4d8aae19c571 # v3
        with:
          sarif_file: ../results
