name: 'Electronegativity'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - uses: doyensec/electronegativity-action@v2.0

      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ../results
