# This workflow will publish a package to GitHub Releases when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Electron Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          # - macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version-file: .nvmrc

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@92327c67bc45ff7c38bf55d8aa8c4d75b7ea38e7 # v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # Force releases, even if the release exists on Github already.
          release: false
          args: --publish=always

          # Allow some retries, the github api can be a bit flaky.
          max_attempts: 3
