# This workflow will publish a package to GitHub Releases when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Electron Release

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  publish-github:
    runs-on: ubuntu-latest
    container:
      image: electronuserland/builder:14-wine-mono
    steps:
      - run: npm i -g npm@8
      - uses: actions/checkout@v2
      - run: |-
          whoami
          ls -l .husky
          npm ci
      - run: npm run build
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
