name: Viteshot

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [main]

jobs:
  screenshot:
    name: 'screenshot-${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          token: ${{ secrets.VITESHOT_PAT }}
          persist-credentials: true
          lfs: true
      - name: Use Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version-file: .nvmrc
      - name: Cache Node.js modules
        uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3
        with:
          path: |
            **/node_modules
            ~/.cache/ms-playwright
            ~/Caches/ms-playwright
          key: ${{ runner.OS }}-v1-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-v1-npm-
      - run: npm ci
      - run: npm run build
      - run: npx --no-install playwright install
      - name: Run viteshot
        run: npm run viteshot:ci
      - name: Erase Vite caches
        run: npx --no-install rimraf "**/node_modules/.vite"
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        if: failure()
        with:
          name: screenshots
          path: '**/__screenshots__/'
