name: Viteshot

concurrency:
  group: viteshot-${{ github.ref }}
  cancel-in-progress: true

on:
  # Run viteshot on all Renovate branches and all PR's. If viteshot detects changes it will push to the branch, which
  # should cause Renovate to create a PR.
  push:
    branches: [ 'renovate/**' ]
  pull_request:
    branches: [ main ]

jobs:
  screenshot:
    name: "screenshot-${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x]
        os:
          - ubuntu-latest
          - windows-latest
          # Disabled until we can justify the super expensive osx builds on github actions
          #- macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ~/.cache/ms-playwright
            ~/Caches/ms-playwright
          key: ${{ runner.OS }}-v1-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-v1-npm-
      - run: npm ci
      - run: npm run build
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
      - run: npx --no-install playwright install
      - name: Run viteshot
        run: |
          git fetch
          git checkout $GITHUB_PR_HEAD
          npx --no-install viteshot -p
      - name: Erase Vite caches
        run: npx --no-install rimraf "**/node_modules/.vite"
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: screenshots
          path: "**/__screenshots__/"
